blueprint:
  name: Chauffage – Confort selon heure calculée (événementiel)
  description: >
    Applique automatiquement le preset Confort ou Éco sur un thermostat
    selon un calendrier de présence et une heure de démarrage calculée.
    Le preset et la consigne sont ré-appliqués après redémarrage de Home Assistant.
  domain: automation
  input:
    thermostat:
      name: Thermostat
      selector:
        entity:
          domain: climate

    calendrier_presence:
      name: Calendrier Présence
      selector:
        entity:
          domain: calendar

    calendrier_absence:
      name: Calendrier Absence
      selector:
        entity:
          domain: calendar

    heure_prochaine_chauffe:
      name: Heure de démarrage Confort (Début)
      selector:
        entity:
          domain: input_datetime

    heure_fin_confort:
      name: Heure de fin Confort (Fin)
      selector:
        entity:
          domain: input_datetime

    preset_confort:
      name: Preset Confort
      default: comfort
      selector:
        select:
          options:
            - label: "Confort"
              value: comfort
            - label: "Eco"
              value: eco

    preset_eco:
      name: Preset Éco
      default: eco
      selector:
        select:
          options:
            - label: "Eco"
              value: eco
            - label: "Confort"
              value: comfort

    consigne_confort:
      name: Consigne confort
      selector:
        entity:
          domain: number

    consigne_eco:
      name: Consigne éco
      selector:
        entity:
          domain: number

mode: single

variables:
  thermostat_entity: !input thermostat
  calendrier_presence_entity: !input calendrier_presence
  calendrier_absence_entity: !input calendrier_absence
  heure_prochaine_chauffe_entity: !input heure_prochaine_chauffe
  heure_fin_confort_entity: !input heure_fin_confort
  preset_confort_value: !input preset_confort
  preset_eco_value: !input preset_eco
  consigne_confort_value: !input consigne_confort
  consigne_eco_value: !input consigne_eco

trigger:
  - platform: homeassistant
    event: start
    id: ha_start

  - platform: state
    entity_id: !input calendrier_presence

  - platform: state
    entity_id: !input calendrier_absence

  - platform: state
    entity_id: !input heure_prochaine_chauffe

  - platform: state
    entity_id: !input heure_fin_confort

  - platform: time_pattern
    minutes: "/5"

  - platform: time
    at: !input heure_prochaine_chauffe

condition:
  - condition: template
    value_template: >
      {{ not is_state(calendrier_absence_entity, 'on') }}

action:
  - choose:
      - conditions:
          - condition: trigger
            id: ha_start
        sequence:
          - delay: "00:02:00"

  - variables:
      ha_restarted: >
        {{ trigger is defined and trigger.id == 'ha_start' }}

      ts_start: >
        {{ as_timestamp(states(heure_prochaine_chauffe_entity), default=0) }}

      ts_end: >
        {{ as_timestamp(states(heure_fin_confort_entity), default=0) }}

      comfort_window: >
        {% set now_ts = now().timestamp() %}
        {{ (ts_start > 0 and ts_end > 0 and now_ts >= ts_start and now_ts < ts_end)
           or is_state(calendrier_presence_entity, 'on') }}

      desired_preset: >
        {{ preset_confort_value if comfort_window else preset_eco_value }}

      desired_temperature: >
        {{ states(consigne_confort_value if comfort_window else consigne_eco_value) | float(0) }}

      current_preset: >
        {{ state_attr(thermostat_entity, 'preset_mode') }}

  - condition: template
    value_template: >
      {{ current_preset != desired_preset or ha_restarted }}

  # Ordre sûr pour les thermostats

  - service: climate.set_temperature
    target:
      entity_id: !input thermostat
    data:
      temperature: "{{ desired_temperature }}"

  - service: climate.set_preset_mode
    target:
      entity_id: !input thermostat
    data:
      preset_mode: "{{ desired_preset }}"

  - service: climate.set_hvac_mode
    target:
      entity_id: !input thermostat
    data:
      hvac_mode: heat
