blueprint:
  name: Chauffage – Confort selon heure calculée (événementiel)
  description: >
    Applique automatiquement le preset Confort ou Éco sur un thermostat
    selon un calendrier de présence et une heure de démarrage calculée.
    Le preset est ré-appliqué après redémarrage de Home Assistant.
  domain: automation
  input:
    thermostat:
      name: Thermostat
      selector:
        entity:
          domain: climate

    calendrier_presence:
      name: Calendrier Présence
      selector:
        entity:
          domain: calendar

    calendrier_absence:
      name: Calendrier Absence
      selector:
        entity:
          domain: calendar

    heure_prochaine_chauffe:
      name: Heure de démarrage Confort
      selector:
        entity:
          domain: input_datetime

    preset_confort:
      name: Preset Confort
      default: comfort
      selector:
        select:
          options:
            - label: "Confort"
              value: comfort
            - label: "Eco"
              value: eco

    preset_eco:
      name: Preset Éco
      default: eco
      selector:
        select:
          options:
            - label: "Eco"
              value: eco
            - label: "Confort"
              value: comfort

mode: single

variables:
  thermostat_entity: !input thermostat
  calendrier_presence_entity: !input calendrier_presence
  calendrier_absence_entity: !input calendrier_absence
  heure_prochaine_chauffe_entity: !input heure_prochaine_chauffe
  preset_confort_value: !input preset_confort
  preset_eco_value: !input preset_eco

trigger:
  - platform: homeassistant
    event: start
    id: ha_start

  - platform: state
    entity_id: !input calendrier_presence

  - platform: state
    entity_id: !input calendrier_absence

  - platform: state
    entity_id: !input heure_prochaine_chauffe

condition:
  - condition: state
    entity_id: !input calendrier_absence
    state: "off"

action:
  - choose:
      - conditions:
          - condition: trigger
            id: ha_start
        sequence:
          - delay: "00:02:00"

  - variables:
      ha_restarted: >
        {{ trigger is defined and trigger.id == 'ha_start' }}
      comfort_window: >
        {% set start_raw = states(heure_prochaine_chauffe_entity) %}
        {% set ts_start = start_raw not in ['unknown', 'unavailable', 'none', '']
             and as_local(today_at(start_raw)) or none %}
        {% set end_raw = state_attr(calendrier_presence_entity, 'end_time') %}
        {% set ts_end = end_raw and as_local(as_datetime(end_raw)) or none %}
        {{ is_state(calendrier_presence_entity, 'on')
           and ts_start and ts_end
           and now() >= ts_start
           and now() < ts_end }}

      desired_preset: >
        {{ preset_confort_value if comfort_window else preset_eco_value }}

      current_preset: >
        {{ state_attr(thermostat_entity, 'preset_mode') }}

  - condition: template
    value_template: >
      {{ current_preset != desired_preset or ha_restarted == 'True' }}

  - service: climate.set_preset_mode
    target:
      entity_id: !input thermostat
    data:
      preset_mode: "{{ desired_preset }}"
  - service: climate.set_hvac_mode
    target:
      entity_id: !input thermostat
    data:
      hvac_mode: "heat"
