blueprint:
  name: Chauffage – Global (anticipation + pilotage + auto-apprentissage ROBUSTE)
  description: >
    Anticipation de chauffe basée sur calendrier + vitesse de chauffe,
    pilotage Confort / Éco, et auto-apprentissage robuste déclenché
    sur l'heure réelle de début de présence (indépendant des états calendar).
  domain: automation

  input:
    thermostat:
      name: Thermostat
      selector:
        entity:
          domain: climate

    calendrier_presence:
      name: Calendrier Présence
      selector:
        entity:
          domain: calendar

    calendrier_absence:
      name: Calendrier Absence
      selector:
        entity:
          domain: calendar

    vitesse_chauffe_sensor:
      name: Vitesse de chauffe (°C/min)
      selector:
        entity:
          domain: sensor

    consigne_confort:
      name: Consigne Confort
      selector:
        entity:
          domain: number

    consigne_eco:
      name: Consigne Éco
      selector:
        entity:
          domain: number

    preset_confort:
      name: Preset Confort
      default: comfort
      selector:
        select:
          options:
            - label: Confort
              value: comfort
            - label: Eco
              value: eco

    preset_eco:
      name: Preset Éco
      default: eco
      selector:
        select:
          options:
            - label: Eco
              value: eco
            - label: Confort
              value: comfort

    facteur_chauffe:
      name: Facteur auto-apprenant
      selector:
        entity:
          domain: input_number

    temp_exterieure:
      name: Température extérieure
      selector:
        entity:
          domain: sensor

    temp_ext_reference:
      name: Température extérieure de référence
      default: 10
      selector:
        number:
          min: -10
          max: 20
          step: 1

    coeff_ext:
      name: Sensibilité extérieure (% / °C)
      default: 5
      selector:
        number:
          min: 0
          max: 10
          step: 1

    inertie_max_minutes:
      name: Anticipation maximale (min)
      default: 180
      selector:
        number:
          min: 0
          max: 600
          step: 5

    inertie_min_minutes:
      name: Anticipation minimale (min)
      default: 15
      selector:
        number:
          min: 0
          max: 120
          step: 5

    prochaine_chauffe:
      name: Début Confort calculé
      selector:
        entity:
          domain: input_datetime

    fin_confort:
      name: Fin Confort
      selector:
        entity:
          domain: input_datetime

    dernier_apprentissage:
      name: Dernier apprentissage
      selector:
        entity:
          domain: input_datetime

    apprentissage_zone_neutre:
      name: Zone neutre (°C)
      default: 0.2
      selector:
        number:
          min: 0
          max: 1
          step: 0.05

    apprentissage_step_percent:
      name: Pas apprentissage (%)
      default: 3
      selector:
        number:
          min: 0
          max: 10
          step: 1

    apprentissage_facteur_min:
      name: Facteur min
      default: 0.8
      selector:
        number:
          min: 0.5
          max: 2
          step: 0.05

    apprentissage_facteur_max:
      name: Facteur max
      default: 2.0
      selector:
        number:
          min: 0.5
          max: 3
          step: 0.05

mode: single

trigger:
  - platform: homeassistant
    event: start

  - platform: state
    entity_id: !input calendrier_presence

  - platform: state
    entity_id: !input calendrier_absence

  - platform: time_pattern
    minutes: "/5"

action:
  - variables:
      thermostat_entity: !input thermostat
      calendrier_presence_entity: !input calendrier_presence
      calendrier_absence_entity: !input calendrier_absence
      vitesse_entity: !input vitesse_chauffe_sensor
      consigne_confort_entity: !input consigne_confort
      consigne_eco_entity: !input consigne_eco
      facteur_entity: !input facteur_chauffe
      temp_ext_entity: !input temp_exterieure
      temp_ext_ref: !input temp_ext_reference
      coeff_ext_val: !input coeff_ext
      inertie_max: !input inertie_max_minutes
      inertie_min: !input inertie_min_minutes
      prochaine_chauffe_entity: !input prochaine_chauffe
      fin_confort_entity: !input fin_confort
      dernier_apprentissage_entity: !input dernier_apprentissage
      preset_confort_value: !input preset_confort
      preset_eco_value: !input preset_eco

      stored_end_ts: "{{ as_timestamp(states(fin_confort_entity), default=none) }}"

  - condition: template
    value_template: "{{ not is_state(calendrier_absence_entity, 'on') }}"

  - service: calendar.get_events
    target:
      entity_id: !input calendrier_presence
    data:
      start_date_time: "{{ now().isoformat() }}"
      end_date_time: "{{ (now() + timedelta(days=7)).isoformat() }}"
    response_variable: presence_events

  - variables:
      payload: "{{ presence_events.get(calendrier_presence_entity) }}"
      now_iso: "{{ now().isoformat() }}"

      event: >
        {% if payload %}
          {{ payload.events
             | selectattr('start','<=',now_iso)
             | selectattr('end','>',now_iso)
             | list
             | first
             or
             (payload.events
              | selectattr('start','>',now_iso)
              | list
              | first) }}
        {% else %}{{ none }}{% endif %}

      debut_presence: "{{ as_timestamp(event.start) if event else none }}"
      fin_presence: "{{ as_timestamp(event.end) if event else none }}"

  - variables:
      temp_actuelle: "{{ state_attr(thermostat_entity,'current_temperature') | float(0) }}"
      temp_cible: "{{ states(consigne_confort_entity) | float(0) }}"
      delta: "{{ temp_cible - temp_actuelle }}"

      vitesse_raw: "{{ states(vitesse_entity) | replace(',', '.') | float(0) }}"
      vitesse: "{{ [vitesse_raw, 0.01] | max }}"

      facteur_base: "{{ states(facteur_entity) | float(1.2) }}"
      temp_ext: "{{ states(temp_ext_entity) | float(temp_ext_ref) }}"
      delta_ext: "{{ temp_ext_ref - temp_ext }}"
      facteur_ext: >
        {% if delta_ext > 0 %}
          {{ [1 + delta_ext * coeff_ext_val / 100, 1.3] | min }}
        {% else %}1{% endif %}
      facteur: "{{ facteur_base * facteur_ext }}"

      minutes: >
        {% if delta > 0.1 %}
          {{ (delta / vitesse * facteur) | round(0,'ceil') }}
        {% else %}0{% endif %}

      minutes_final: >
        {% if minutes > 0 %}
          {{ [ [minutes, inertie_min]|max, inertie_max ]|min }}
        {% else %}0{% endif %}

      ts_start: "{{ (debut_presence - minutes_final*60) | int if debut_presence else 0 }}"
      ts_end: "{{ fin_presence | int if fin_presence else 0 }}"

      comfort_window: >
        {% set now_ts = now().timestamp() %}
        {{ ts_start > 0 and ts_end > 0 and now_ts >= ts_start and now_ts < ts_end }}

  - choose:
      - conditions:
          - condition: template
            value_template: "{{ ts_start > 0 and ts_end > 0 }}"
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input prochaine_chauffe
            data:
              timestamp: "{{ ts_start }}"

          - service: input_datetime.set_datetime
            target:
              entity_id: !input fin_confort
            data:
              timestamp: "{{ ts_end }}"

  # ===== PILOTAGE PRESET (LOGIQUE D'ÉTAT) =====
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ comfort_window
                 and state_attr(thermostat_entity,'preset_mode') != preset_confort_value }}
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: "{{ thermostat_entity }}"
            data:
              preset_mode: "{{ preset_confort_value }}"

      - conditions:
          - condition: template
            value_template: >
              {{ not comfort_window
                 and stored_end_ts is not none
                 and now().timestamp() >= stored_end_ts
                 and state_attr(thermostat_entity,'preset_mode') != preset_eco_value }}
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: "{{ thermostat_entity }}"
            data:
              preset_mode: "{{ preset_eco_value }}"

  # ===== APPRENTISSAGE ROBUSTE =====
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ comfort_window
                 and debut_presence is not none
                 and now().timestamp() >= debut_presence
                 and now().timestamp() < debut_presence + 300 }}
        sequence:
          - variables:
              erreur: "{{ temp_cible - temp_actuelle }}"
              facteur_actuel: "{{ states(facteur_entity) | float(1.2) }}"
              step_ratio: "{{ apprentissage_step_percent / 100 }}"
              nouveau_facteur: >
                {% if erreur > apprentissage_zone_neutre %}
                  {{ facteur_actuel * (1 + step_ratio) }}
                {% elif erreur < -apprentissage_zone_neutre %}
                  {{ facteur_actuel * (1 - step_ratio) }}
                {% else %}
                  {{ facteur_actuel }}
                {% endif %}
              facteur_borne: >
                {{ [ [nouveau_facteur, apprentissage_facteur_min]|max,
                     apprentissage_facteur_max ]|min }}

          - condition: template
            value_template: "{{ facteur_borne != facteur_actuel }}"

          - service: input_number.set_value
            target:
              entity_id: !input facteur_chauffe
            data:
              value: "{{ facteur_borne }}"

          - service: input_datetime.set_datetime
            target:
              entity_id: !input dernier_apprentissage
            data:
              timestamp: "{{ debut_presence | int }}"
