blueprint:
  name: Chauffage anticipé VT (inertie + météo + calendrier + absence)
  description: >
    Chauffage anticipé basé sur l'inertie thermique apprise,
    la température extérieure, un calendrier de présence
    et un calendrier d'absence.
  domain: automation
  input:
    thermostat:
      name: Thermostat Versatile
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Capteur de température intérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    inertia_sensor:
      name: Inertie apprise (°C/min)
      selector:
        entity:
          domain: sensor

    inertia_unit:
      name: Unité de dérive (capteur inertie)
      default: "c_per_min"
      selector:
        select:
          options:
            - label: "°C/min"
              value: "c_per_min"
            - label: "°C/h"
              value: "c_per_hour"

    outside_temperature:
      name: Température extérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    calendar_entity:
      name: Calendrier de présence
      selector:
        entity:
          domain: calendar

    calendar_entity_state:
      name: État requis du calendrier de présence
      description: "Choisir si l'automatisation doit être autorisée quand le calendrier de présence est actif (on) ou inactif (off)."
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

    absence_calendar:
      name: Calendrier d'absence
      description: "Vacances, déplacements, etc."
      selector:
        entity:
          domain: calendar

    absence_calendar_state:
      name: État bloquant du calendrier d'absence
      description: "Choisir si l'automatisation doit être bloquée quand le calendrier est actif (on) ou inactif (off)."
      default: "on"
      selector:
        select:
          options:
            - "on"
            - "off"

    presence_preset_on:
      name: Preset si présence active
      description: "Ex: comfort, eco, boost"
      selector:
        select:
          options:
            - comfort
            - eco
            - boost

    presence_preset_off:
      name: Preset si présence inactive
      description: "Ex: comfort, eco, boost"
      selector:
        select:
          options:
            - comfort
            - eco
            - boost

    comfort_temperature_number:
      name: Température preset comfort (number)
      description: "Entité number exposée par Versatile Thermostat (ex: number.central_configuration_preset_comfort_temp)"
      selector:
        entity:
          domain: number

    eco_temperature_number:
      name: Température preset eco (number)
      description: "Entité number exposée par Versatile Thermostat"
      selector:
        entity:
          domain: number

    boost_temperature_number:
      name: Température preset boost (number)
      description: "Entité number exposée par Versatile Thermostat"
      selector:
        entity:
          domain: number

    earliest_start:
      name: Heure minimale de démarrage
      default: "05:00:00"
      selector:
        time: {}

    max_inertia:
      name: Inertie maximale (minutes)
      default: 180
      selector:
        number:
          min: 30
          max: 300
          step: 10
          unit_of_measurement: "min"

    preheat_start_time_number:
      name: Entité (input_number) pour stocker le timestamp de début de chauffe
      description: "Timestamp Unix en secondes (début de chauffe calculé)"
      default: ""
      selector:
        entity:
          domain: input_number

mode: single

variables:
  preheat_start_ts: >
    {% set event = state_attr(input.calendar_entity, 'start_time') %}
    {% if event %}
      {% set cible = as_datetime(event) %}
      {% set rate_raw = states(input.inertia_sensor) %}
      {% set rate_in = (rate_raw | replace(',', '.')) | float(0) %}
      {% set inertia_unit = input.inertia_unit %}
      {% if inertia_unit == 'c_per_hour' %}
        {% set rate = (rate_in / 60) %}
      {% else %}
        {% set rate = rate_in %}
      {% endif %}
      {% set temp_actuelle = states(input.temperature_sensor) | float(0) %}
      {% set preset = input.presence_preset_on %}
      {% if preset == 'comfort' %}
        {% set consigne = states(input.comfort_temperature_number) | float(0) %}
      {% elif preset == 'eco' %}
        {% set consigne = states(input.eco_temperature_number) | float(0) %}
      {% elif preset == 'boost' %}
        {% set consigne = states(input.boost_temperature_number) | float(0) %}
      {% else %}
        {% set consigne = state_attr(input.thermostat, 'temperature') | float(0) %}
      {% endif %}
      {% set delta = consigne - temp_actuelle %}
      {% set max_i = input.max_inertia | int %}
      {% if rate > 0 and delta > 0 %}
        {% set minutes_needed = (delta / rate) | round(0, 'ceil') | int %}
        {% set minutes = [minutes_needed, max_i] | min %}
      {% else %}
        {% set minutes = 60 %}
      {% endif %}
      {{ (as_timestamp(cible) - (minutes * 60)) | int }}
    {% else %}
      {{ none }}
    {% endif %}

trigger:
  - platform: template
    id: preheat
    value_template: >
      {{ preheat_start_ts is not none and as_timestamp(now()) >= (preheat_start_ts | int) }}

  - platform: state
    id: presence_on
    entity_id: !input calendar_entity
    to: "on"

  - platform: state
    id: presence_off
    entity_id: !input calendar_entity
    to: "off"

condition:
  # ❌ Blocage si absence active
  - condition: state
    entity_id: !input absence_calendar
    state: !input absence_calendar_state

action:
  - choose:
      - conditions:
          - condition: trigger
            id: presence_off
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_off

      - conditions:
          - condition: trigger
            id: presence_on
        sequence:
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_on

      - conditions:
          - condition: trigger
            id: preheat
          - condition: state
            entity_id: !input calendar_entity
            state: "on"
          - condition: time
            after: !input earliest_start
          - condition: template
            value_template: >
              {% set temp_actuelle = states(input.temperature_sensor) | float %}
              {% set preset = input.presence_preset_on %}
              {% if preset == 'comfort' %}
                {% set consigne = states(input.comfort_temperature_number) | float(0) %}
              {% elif preset == 'eco' %}
                {% set consigne = states(input.eco_temperature_number) | float(0) %}
              {% elif preset == 'boost' %}
                {% set consigne = states(input.boost_temperature_number) | float(0) %}
              {% else %}
                {% set consigne = state_attr(input.thermostat, 'temperature') | float(0) %}
              {% endif %}
              {{ temp_actuelle < (consigne - 0.2) }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (input.preheat_start_time_number | default('')) != '' }}
                sequence:
                  - service: input_number.set_value
                    data:
                      entity_id: >
                        {{ input.preheat_start_time_number | default('') }}
                      value: >
                        {{ (preheat_start_ts | int(0)) }}
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_on
