blueprint:
  name: Chauffage anticipé VT (inertie + calendrier + absence)
  description: >
    Chauffage anticipé basé sur l'inertie thermique apprise,
    la température intérieure, un calendrier de présence
    et un calendrier d'absence.
  domain: automation
  input:
    thermostat:
      name: Thermostat Versatile
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Capteur de température intérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    inertia_sensor:
      name: Inertie apprise
      description: "Dérive thermique (°C/min ou °C/h)"
      selector:
        entity:
          domain: sensor

    inertia_unit:
      name: Unité de l’inertie
      default: "c_per_min"
      selector:
        select:
          options:
            - label: "°C/min"
              value: "c_per_min"
            - label: "°C/h"
              value: "c_per_hour"

    calendar_entity:
      name: Calendrier de présence
      selector:
        entity:
          domain: calendar

    absence_calendar:
      name: Calendrier d'absence
      selector:
        entity:
          domain: calendar

    presence_preset_on:
      name: Preset en cas de présence
      selector:
        select:
          options: [comfort, eco, boost]

    presence_preset_off:
      name: Preset en cas d'absence
      selector:
        select:
          options: [comfort, eco, boost]

    comfort_temperature_number:
      name: Température comfort
      selector:
        entity:
          domain: number

    eco_temperature_number:
      name: Température eco
      selector:
        entity:
          domain: number

    boost_temperature_number:
      name: Température boost
      selector:
        entity:
          domain: number

    earliest_start:
      name: Heure minimale de démarrage
      default: "05:00:00"
      selector:
        time: {}

    max_inertia:
      name: Inertie maximale (minutes)
      default: 180
      selector:
        number:
          min: 30
          max: 300
          step: 10
          unit_of_measurement: min

    preheat_start_time_text:
      name: Stockage du timestamp de préchauffe
      description: "input_text pour stocker le timestamp Unix calculé"
      selector:
        entity:
          domain: input_text

mode: single

variables:
  target_temperature: >
    {% if input.presence_preset_on == 'comfort' %}
      {{ states(input.comfort_temperature_number) | float(0) }}
    {% elif input.presence_preset_on == 'eco' %}
      {{ states(input.eco_temperature_number) | float(0) }}
    {% elif input.presence_preset_on == 'boost' %}
      {{ states(input.boost_temperature_number) | float(0) }}
    {% else %}
      {{ state_attr(input.thermostat, 'temperature') | float(0) }}
    {% endif %}

  preheat_start_ts: >
    {% set event = state_attr(input.calendar_entity, 'start_time') %}
    {% if not event %}
      {{ none }}
    {% else %}
      {% set cible = as_datetime(event) %}
      {% set temp_actuelle = states(input.temperature_sensor) | float(0) %}
      {% set delta = target_temperature - temp_actuelle %}
      {% set rate_raw = states(input.inertia_sensor) | replace(',', '.') | float(0) %}

      {% if input.inertia_unit == 'c_per_hour' %}
        {% set rate = rate_raw / 60 %}
      {% else %}
        {% set rate = rate_raw %}
      {% endif %}

      {% set max_i = input.max_inertia | int %}
      {% if rate > 0 and delta > 0 %}
        {% set minutes_needed = (delta / rate) | round(0, 'ceil') | int %}
        {% set minutes = [minutes_needed, max_i] | min %}
      {% else %}
        {% set minutes = max_i %}
      {% endif %}

      {% set ts_calc = as_timestamp(cible) - (minutes * 60) %}
      {% set ts_earliest = today_at(input.earliest_start) | as_timestamp %}
      {{ [ts_calc, ts_earliest] | max | int }}
    {% endif %}

trigger:
  - platform: template
    id: preheat
    value_template: >
      {{
        preheat_start_ts is not none and
        as_timestamp(now()) >= preheat_start_ts and
        as_timestamp(now()) < preheat_start_ts + 60
      }}

  - platform: state
    id: presence_on
    entity_id: !input calendar_entity
    to: "on"

  - platform: state
    id: presence_off
    entity_id: !input calendar_entity
    to: "off"

condition:
  # Blocage si absence active
  - condition: not
    conditions:
      - condition: state
        entity_id: !input absence_calendar
        state: "on"

action:
  - choose:
      # Présence OFF → preset absence
      - conditions:
          - condition: trigger
            id: presence_off
        sequence:
          - condition: template
            value_template: >
              {{ state_attr(input.thermostat, 'preset_mode') != input.presence_preset_off }}
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_off

      # Présence ON → preset présence
      - conditions:
          - condition: trigger
            id: presence_on
        sequence:
          - condition: template
            value_template: >
              {{ state_attr(input.thermostat, 'preset_mode') != input.presence_preset_on }}
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_on

      # Préchauffe anticipée
      - conditions:
          - condition: trigger
            id: preheat
          - condition: state
            entity_id: !input calendar_entity
            state: "on"
          - condition: template
            value_template: >
              {{ states(input.temperature_sensor) | float(0) < target_temperature - 0.2 }}
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input preheat_start_time_text
            data:
              value: "{{ preheat_start_ts }}"
          - condition: template
            value_template: >
              {{ state_attr(input.thermostat, 'preset_mode') != input.presence_preset_on }}
          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input presence_preset_on
