blueprint:
  name: Chauffage anticipé VT (auto-apprenant + météo)
  description: >
    Chauffage anticipé basé sur le slope Versatile Thermostat,
    pondération météo et apprentissage automatique de l'inertie.
  domain: automation
  input:
    thermostat:
      name: Thermostat Versatile
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Température intérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outside_temperature:
      name: Température extérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    inertia_sensor:
      name: Slope VT
      selector:
        entity:
          domain: sensor

    inertia_unit:
      name: Unité du slope
      default: c_per_hour
      selector:
        select:
          options:
            - label: "°C/min"
              value: c_per_min
            - label: "°C/h"
              value: c_per_hour

    calendar_entity:
      name: Calendrier de présence
      selector:
        entity:
          domain: calendar

    absence_calendar:
      name: Calendrier d'absence
      selector:
        entity:
          domain: calendar

    comfort_temperature_number:
      name: Consigne comfort
      selector:
        entity:
          domain: number

    earliest_start:
      name: Heure minimale de chauffe
      default: "05:00:00"
      selector:
        time: {}

    max_inertia:
      name: Inertie max (minutes)
      default: 180
      selector:
        number:
          min: 30
          max: 300
          step: 10

    learning_factor:
      name: Facteur d’apprentissage
      selector:
        entity:
          domain: input_number

    preheat_start_time_text:
      name: Stockage timestamp préchauffe
      selector:
        entity:
          domain: input_text

mode: single

variables:
  target_temp: "{{ states(input.comfort_temperature_number) | float(0) }}"

  event_start_ts: >
    {% set event = state_attr(input.calendar_entity, 'start_time') %}
    {% if not event %}
      {{ none }}
    {% else %}
      {{ as_timestamp(as_datetime(event)) | int }}
    {% endif %}

  preheat_start_ts: >
    {% set event = state_attr(input.calendar_entity, 'start_time') %}
    {% if not event %}
      {{ none }}
    {% else %}
      {% set cible = as_datetime(event) %}
      {% set temp_now = states(input.temperature_sensor) | float(0) %}
      {% set delta = target_temp - temp_now %}
      {% set raw = states(input.inertia_sensor) | replace(',', '.') | float(0) %}

      {% if input.inertia_unit == 'c_per_hour' %}
        {% set rate = raw / 60 %}
      {% else %}
        {% set rate = raw %}
      {% endif %}

      {# Pondération météo #}
      {% set ext = states(input.outside_temperature) | float(0) %}
      {% if ext < 0 %}
        {% set rate = rate * 0.8 %}
      {% elif ext > 10 %}
        {% set rate = rate * 1.15 %}
      {% endif %}

      {# Apprentissage #}
      {% set rate = rate * (states(input.learning_factor) | float(1)) %}

      {% set max_i = input.max_inertia | int %}
      {% if rate > 0 and delta > 0 %}
        {% set minutes = [(delta / rate) | round(0, 'ceil'), max_i] | min %}
      {% else %}
        {% set minutes = max_i %}
      {% endif %}

      {% set ts_calc = as_timestamp(cible) - minutes * 60 %}
      {% set ts_min = today_at(input.earliest_start) | as_timestamp %}
      {{ [ts_calc, ts_min] | max | int }}
    {% endif %}

trigger:
  - platform: template
    id: preheat
    value_template: >
      {{
        preheat_start_ts is not none and
        as_timestamp(now()) >= preheat_start_ts and
        as_timestamp(now()) < preheat_start_ts + 60
      }}

  - platform: time_pattern
    id: preheat_catchup
    minutes: "/1"

  - platform: numeric_state
    id: learning
    entity_id: !input temperature_sensor
    above: !input comfort_temperature_number

condition:
  - condition: not
    conditions:
      - condition: state
        entity_id: !input absence_calendar
        state: "on"

action:
  - choose:
      # 🔥 Rattrapage préchauffe (si HA a raté la minute de déclenchement)
      - conditions:
          - condition: trigger
            id: preheat_catchup
          - condition: state
            entity_id: !input calendar_entity
            state: "on"
          - condition: template
            value_template: >
              {% set planned = states(input.preheat_start_time_text) | int(0) %}
              {{
                preheat_start_ts is not none and
                event_start_ts is not none and
                as_timestamp(now()) >= preheat_start_ts + 60 and
                as_timestamp(now()) < event_start_ts and
                planned != (preheat_start_ts | int)
              }}
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input preheat_start_time_text
            data:
              value: "{{ preheat_start_ts }}"
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ target_temp }}"

      # 🔥 Préchauffe
      - conditions:
          - condition: trigger
            id: preheat
          - condition: state
            entity_id: !input calendar_entity
            state: "on"
        sequence:
          - service: input_text.set_value
            target:
              entity_id: !input preheat_start_time_text
            data:
              value: "{{ preheat_start_ts }}"
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ target_temp }}"

      # 🧠 Apprentissage
      - conditions:
          - condition: trigger
            id: learning
        sequence:
          - variables:
              planned: "{{ states(input.preheat_start_time_text) | int(0) }}"
              age_min: "{{ (as_timestamp(now()) - planned) / 60 }}"
              factor: "{{ states(input.learning_factor) | float(1) }}"
          - service: input_number.set_value
            target:
              entity_id: !input learning_factor
            data:
              value: >
                {% if planned == 0 or age_min < 0 or age_min > 360 %}
                  {{ factor | round(2) }}
                {% elif age_min > 5 %}
                  {{ [factor * 0.98, 0.7] | max | round(2) }}
                {% elif age_min < -5 %}
                  {{ [factor * 1.02, 1.3] | min | round(2) }}
                {% else %}
                  {{ factor | round(2) }}
                {% endif %}
