blueprint:
  name: Chauffage anticipé VT (auto-apprenant + météo)
  description: >
    Chauffage anticipé basé sur le slope Versatile Thermostat,
    pondération météo et apprentissage automatique de l'inertie.
  domain: automation

  input:
    thermostat:
      name: Thermostat Versatile
      selector:
        entity:
          domain: climate

    temperature_sensor:
      name: Température intérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    outside_temperature:
      name: Température extérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    inertia_sensor:
      name: Slope VT
      selector:
        entity:
          domain: sensor

    inertia_unit:
      name: Unité du slope
      default: c_per_hour
      selector:
        select:
          options:
            - label: "°C/min"
              value: c_per_min
            - label: "°C/h"
              value: c_per_hour

    calendar_entity:
      name: Calendrier de présence
      selector:
        entity:
          domain: calendar

    absence_calendar:
      name: Calendrier d'absence
      selector:
        entity:
          domain: calendar

    comfort_temperature_number:
      name: Consigne comfort
      selector:
        entity:
          domain: number

    earliest_start:
      name: Heure minimale de chauffe
      default: "05:00:00"
      selector:
        time: {}

    max_inertia:
      name: Inertie max (minutes)
      default: 180
      selector:
        number:
          min: 30
          max: 300
          step: 10

    learning_factor:
      name: Facteur d’apprentissage
      selector:
        entity:
          domain: input_number

    preheat_start_datetime:
      name: Stockage début préchauffe
      selector:
        entity:
          domain: input_datetime

mode: single

variables:
  target_temp: "{{ states(input.comfort_temperature_number) | float(0) }}"

  event_start_ts: >
    {% set ev = state_attr(input.calendar_entity, 'start_time') %}
    {{ as_timestamp(ev) if ev else none }}

  preheat_start_ts: >
    {% if event_start_ts is none %}
      {{ none }}
    {% else %}
      {% set temp_now = states(input.temperature_sensor) | float(0) %}
      {% set delta = target_temp - temp_now %}

      {% set raw = states(input.inertia_sensor) | replace(',', '.') | float(0) %}
      {% if raw <= 0 %}
        {% set raw = 0.05 %}
      {% endif %}

      {% if input.inertia_unit == 'c_per_hour' %}
        {% set rate = raw / 60 %}
      {% else %}
        {% set rate = raw %}
      {% endif %}

      {% set ext = states(input.outside_temperature) | float(0) %}
      {% if ext < 0 %}
        {% set rate = rate * 0.8 %}
      {% elif ext > 10 %}
        {% set rate = rate * 1.15 %}
      {% endif %}

      {% set lf = states(input.learning_factor) | float(1) | clamp(0.7, 1.3) %}
      {% set rate = rate * lf %}

      {% set max_i = input.max_inertia | int %}
      {% if rate > 0 and delta > 0 %}
        {% set minutes = [(delta / rate) | round(0,'ceil'), max_i] | min %}
      {% else %}
        {% set minutes = max_i %}
      {% endif %}

      {% set ts_calc = event_start_ts - minutes * 60 %}
      {% set ts_min = today_at(input.earliest_start) | as_timestamp %}
      {{ [ts_calc, ts_min] | max | int }}
    {% endif %}

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: template
    value_template: "{{ event_start_ts is not none }}"
  - condition: not
    conditions:
      - condition: state
        entity_id: !input absence_calendar
        state: "on"

action:
  # 💾 Stockage systématique du préchauffe calculé
  - variables:
      stored_preheat_ts: >
        {% set val = states(input.preheat_start_datetime) %}
        {% if val not in ['unknown','unavailable',''] %}
          {{ as_timestamp(val) }}
        {% else %}
          0
        {% endif %}
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ preheat_start_ts is not none and preheat_start_ts != stored_preheat_ts }}
        sequence:
          - service: input_datetime.set_datetime
            target:
              entity_id: !input preheat_start_datetime
            data:
              timestamp: "{{ preheat_start_ts }}"

  # 🔥 Démarrage chauffage
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ preheat_start_ts is not none
                 and now().timestamp() >= preheat_start_ts
                 and now().timestamp() < event_start_ts }}
        sequence:
          - service: climate.set_temperature
            target:
              entity_id: !input thermostat
            data:
              temperature: "{{ target_temp }}"

  # 🧠 Apprentissage
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ states(input.temperature_sensor) | float(0)
                 > states(input.comfort_temperature_number) | float(0)
                 and stored_preheat_ts > 0 }}
        sequence:
          - variables:
              age_min: "{{ (now().timestamp() - stored_preheat_ts) / 60 }}"
              factor: "{{ states(input.learning_factor) | float(1) }}"
          - service: input_number.set_value
            target:
              entity_id: !input learning_factor
            data:
              value: >
                {% if age_min > 360 %}
                  {{ factor | round(2) }}
                {% elif age_min > 5 %}
                  {{ [factor * 0.98, 0.7] | max | round(2) }}
                {% elif age_min < -5 %}
                  {{ [factor * 1.02, 1.3] | min | round(2) }}
                {% else %}
                  {{ factor | round(2) }}
                {% endif %}
