blueprint:
  name: VTherm – Prédiction de chauffe auto-apprenante (Présence / Absence)
  description: >
    Anticipe le passage en preset Confort d’un Versatile Thermostat
    en fonction de la température actuelle, de la météo extérieure,
    d’un calendrier de présence et d’un calendrier d’absence.
    Retour automatique en Eco à la fin de la présence.
    Utilise des paramètres auto-appris (input_number).
  domain: automation
  input:
    thermostat:
      name: Thermostat Versatile
      selector:
        entity:
          domain: climate

    calendrier_presence:
      name: Calendrier Présence
      selector:
        entity:
          domain: calendar

    calendrier_absence:
      name: Calendrier Absence
      selector:
        entity:
          domain: calendar

    heure_predite_chauffe:
      name: Heure prédite de démarrage chauffe (optionnel)
      description: input_datetime contenant l'heure de démarrage anticipée. Si renseignée, elle est utilisée en priorité à la place du calcul basé sur l'heure du calendrier.
      selector:
        entity:
          domain: input_datetime

    temperature_exterieure:
      name: Capteur température extérieure
      selector:
        entity:
          domain: sensor
          device_class: temperature

    preset_confort:
      name: Preset Confort
      default: comfort
      selector:
        select:
          options:
            - label: "Eco"
              value: eco
            - label: "Comfort"
              value: comfort
            - label: "Eco"
              value: eco

    preset_eco:
      name: Preset Éco
      default: eco
      selector:
        select:
          options:
            - label: "Eco"
              value: eco
            - label: "Comfort"
              value: comfort
            - label: "Eco"
              value: eco

    vitesse_chauffe_apprise:
      name: Vitesse de chauffe apprise
      description: input_number mis à jour automatiquement
      selector:
        entity:
          domain: input_number

    influence_froid_apprise:
      name: Influence du froid apprise
      description: input_number mis à jour automatiquement
      selector:
        entity:
          domain: input_number

    seuil_temperature_froid:
      name: Seuil météo neutre (°C)
      default: 15
      selector:
        number:
          min: 0
          max: 20
          step: 1

    temps_inertie_minutes:
      name: Temps d'inertie (minutes)
      description: "Temps minimum d'anticipation si la prédiction ne peut pas être calculée (ex. vitesse=0). Mettre 0 pour appliquer strictement l'heure du calendrier."
      default: 30
      selector:
        number:
          min: 0
          max: 180
          step: 5

trigger:
  - platform: time_pattern
    id: time_pattern
    minutes: "/5"

  - platform: state
    id: absence_on
    entity_id: !input calendrier_absence
    from: "off"
    to: "on"

  - platform: state
    id: state
    entity_id: !input calendrier_presence
    from: "on"
    to: "off"

mode: single

action:
  - choose:
      # 🚫 ABSENCE : FORCER ÉCO
      - conditions:
          - condition: trigger
            id: absence_on

        sequence:
          - variables:
              thermostat: !input thermostat
              preset_eco_value: !input preset_eco

          - condition: template
            value_template: >
              {{ state_attr(thermostat, 'preset_mode') != preset_eco_value }}

          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input preset_eco
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: "heat"

      # 🔥 ANTICIPATION CHAUFFE
      - conditions:
          - condition: trigger
            id: time_pattern

          - condition: state
            entity_id: !input calendrier_absence
            state: "off"

        sequence:
          - variables:
              thermostat: !input thermostat
              calendrier_presence_entity: !input calendrier_presence
              heure_predite_chauffe_entity: !input heure_predite_chauffe
              temperature_exterieure_entity: !input temperature_exterieure
              vitesse_chauffe_apprise_entity: !input vitesse_chauffe_apprise
              influence_froid_apprise_entity: !input influence_froid_apprise
              preset_confort_value: !input preset_confort
              preset_eco_value: !input preset_eco
              seuil_temperature_froid_value: !input seuil_temperature_froid
              temps_inertie_minutes_value: !input temps_inertie_minutes

              temp_actuelle: >
                {{ state_attr(thermostat, 'current_temperature') | float }}

              temp_cible: >
                {{ state_attr(thermostat, 'temperature') | float }}

              temp_ext: >
                {{ states(temperature_exterieure_entity) | float(0) }}

              vitesse: >
                {{ states(vitesse_chauffe_apprise_entity) | float(0) }}

              facteur: >
                {{ states(influence_froid_apprise_entity) | float(0) }}

              delta: >
                {{ (temp_cible - temp_actuelle) | float(0) }}

              correction_froid: >
                {% set seuil = seuil_temperature_froid_value | float %}
                {{ (seuil - temp_ext) * facteur if temp_ext < seuil else 0 }}

              temps_inertie: >
                {{ (temps_inertie_minutes_value | float(0)) * 60 }}

              temps_necessaire: >
                {% if vitesse | float(0) > 0 %}
                  {{ [(((delta / vitesse) + correction_froid) * 3600), 0] | max }}
                {% else %}
                  {{ temps_inertie }}
                {% endif %}

              debut_presence: >
                {{ as_timestamp(state_attr(calendrier_presence_entity, 'start_time'), default=none) }}

              demarrage_predite: >
                {% set val = states(heure_predite_chauffe_entity) %}
                {% if val in ['unknown','unavailable',''] %}
                  {{ none }}
                {% else %}
                  {{ as_timestamp(val, default=none) }}
                {% endif %}

              demarrage_calculee: >
                {{ none if debut_presence is none else (debut_presence - temps_necessaire) }}

              demarrage_chauffe: >
                {{ demarrage_predite if demarrage_predite is not none else demarrage_calculee }}

          - condition: template
            value_template: >
              {{ demarrage_chauffe is not none }}

          - condition: template
            value_template: >
              {{ now().timestamp() >= demarrage_chauffe }}

          - condition: template
            value_template: >
              {{ debut_presence is none or now().timestamp() < debut_presence }}

          - condition: template
            value_template: >
              {{ state_attr(thermostat, 'preset_mode') != preset_confort_value }}

          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input preset_confort
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: "heat"

      # 🌙 RETOUR ÉCO FIN DE PRÉSENCE
      - conditions:
          - condition: trigger
            id: state

        sequence:
          - condition: template
            value_template: >
              {{ state_attr(thermostat, 'preset_mode') != preset_eco_value }}

          - service: climate.set_preset_mode
            target:
              entity_id: !input thermostat
            data:
              preset_mode: !input preset_eco
          - service: climate.set_hvac_mode
            target:
              entity_id: !input thermostat
            data:
              hvac_mode: "heat"
